-- ============================================================================
-- 019_storage.sql
--
-- Supabase Storage buckets and their RLS policies.
--
-- PATH CONVENTIONS (risk R-04). Policies match on path segments, so paths must
-- be generated by one shared helper in the apps. The first segment is always
-- the ownership anchor:
--
--   learning-resources   {course_id}/{module_id}/{lesson_id|_}/{uuid}-{name}
--   learner-submissions  {enrollment_id}/{assessment_id}/{version_id}/{uuid}-{name}
--   payment-proofs       {profile_id}/{invoice_id}/{uuid}-{name}
--   certificates         {certificate_number}.pdf
--   institution-assets   branding/{uuid}-{name}
--
-- storage.foldername(name) returns the segments as an array, 1-indexed.
--
-- NOTE: on a hosted Supabase project the `storage` schema already exists and
-- is owned by `supabase_storage_admin`. Run this file with sufficient
-- privileges (the SQL editor as the project owner is fine).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Buckets. Only institution-assets is public.
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
  ('learning-resources',  'learning-resources',  false),
  ('learner-submissions', 'learner-submissions', false),
  ('payment-proofs',      'payment-proofs',      false),
  ('certificates',        'certificates',        false),
  ('institution-assets',  'institution-assets',  true)
on conflict (id) do update set public = excluded.public;

alter table storage.objects enable row level security;

-- ============================================================================
-- learning-resources
--
-- Read: anyone the resource metadata says may access it. Reusing
-- app.can_access_resource() keeps the file rule and the row rule identical, so
-- they cannot drift apart.
-- Write: academic staff only.
-- ============================================================================
drop policy if exists learning_resources_read on storage.objects;
create policy learning_resources_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'learning-resources'
    and exists (
      select 1 from learning_resources r
       where r.storage_bucket = 'learning-resources'
         and r.storage_path   = storage.objects.name
         and app.can_access_resource(r.id)
    )
  );

drop policy if exists learning_resources_write on storage.objects;
create policy learning_resources_write on storage.objects
  for insert to authenticated
  with check (bucket_id = 'learning-resources' and app.is_academic());

drop policy if exists learning_resources_update on storage.objects;
create policy learning_resources_update on storage.objects
  for update to authenticated
  using  (bucket_id = 'learning-resources' and app.is_academic())
  with check (bucket_id = 'learning-resources' and app.is_academic());

drop policy if exists learning_resources_delete on storage.objects;
create policy learning_resources_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'learning-resources' and app.is_admin());

-- ============================================================================
-- learner-submissions
--
-- First path segment is the enrollment_id. A learner may only write under
-- their OWN enrollment — this is what stops one learner uploading evidence
-- into another learner's folder (brief: "A learner should only upload
-- submissions belonging to their own enrollment/assessment").
-- ============================================================================
drop policy if exists learner_submissions_read on storage.objects;
create policy learner_submissions_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'learner-submissions'
    and (
      app.is_assessor()
      or app.is_admin()
      or app.owns_enrollment((storage.foldername(name))[1]::uuid)
    )
  );

drop policy if exists learner_submissions_write on storage.objects;
create policy learner_submissions_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'learner-submissions'
    and app.owns_enrollment((storage.foldername(name))[1]::uuid)
  );

-- Evidence is immutable once uploaded: a correction is a new version, so
-- there is deliberately no UPDATE policy. Only an admin may delete.
drop policy if exists learner_submissions_delete on storage.objects;
create policy learner_submissions_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'learner-submissions' and app.is_admin());

-- ============================================================================
-- payment-proofs
-- First segment is the profile_id.
-- ============================================================================
drop policy if exists payment_proofs_read on storage.objects;
create policy payment_proofs_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'payment-proofs'
    and (app.is_finance() or (storage.foldername(name))[1]::uuid = auth.uid())
  );

drop policy if exists payment_proofs_write on storage.objects;
create policy payment_proofs_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1]::uuid = auth.uid()
  );

drop policy if exists payment_proofs_delete on storage.objects;
create policy payment_proofs_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'payment-proofs' and app.is_admin());

-- ============================================================================
-- certificates
--
-- Generated by an Edge Function using the service-role key, so no INSERT
-- policy is needed for end users. Learners read their own; public
-- verification is served by a signed URL minted after verify_certificate().
-- ============================================================================
drop policy if exists certificates_read on storage.objects;
create policy certificates_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'certificates'
    and (
      app.is_admin()
      or exists (
        select 1 from certificates c
         where c.storage_path = storage.objects.name
           and c.profile_id  = auth.uid()
      )
    )
  );

-- ============================================================================
-- institution-assets (public bucket: logo, letterhead)
-- ============================================================================
drop policy if exists institution_assets_read on storage.objects;
create policy institution_assets_read on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'institution-assets');

drop policy if exists institution_assets_write on storage.objects;
create policy institution_assets_write on storage.objects
  for insert to authenticated
  with check (bucket_id = 'institution-assets' and app.is_admin());

drop policy if exists institution_assets_update on storage.objects;
create policy institution_assets_update on storage.objects
  for update to authenticated
  using  (bucket_id = 'institution-assets' and app.is_admin())
  with check (bucket_id = 'institution-assets' and app.is_admin());

drop policy if exists institution_assets_delete on storage.objects;
create policy institution_assets_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'institution-assets' and app.is_admin());

-- ============================================================================
-- Upload validation
--
-- Enforces the institution's MIME allow-list and size caps at insert time, so
-- an oversized or disallowed file is rejected by the database rather than by
-- client-side validation alone (brief: "Validate file type, file size").
-- ============================================================================
create or replace function app.validate_resource_upload()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  s     institution_settings%rowtype;
  v_mime text;
  v_size bigint;
begin
  select * into s from institution_settings limit 1;
  if not found then return new; end if;

  v_mime := new.metadata ->> 'mimetype';
  v_size := (new.metadata ->> 'size')::bigint;

  if new.bucket_id = 'learning-resources' then
    if v_mime is not null and not (v_mime = any(s.allowed_resource_mime)) then
      raise exception 'File type % is not permitted for learning resources', v_mime
        using errcode = '23514';
    end if;
    if v_size is not null and v_size > s.max_resource_bytes then
      raise exception 'File exceeds the % byte limit for learning resources', s.max_resource_bytes
        using errcode = '23514';
    end if;

  elsif new.bucket_id in ('learner-submissions', 'payment-proofs') then
    if v_mime is not null and not (v_mime = any(s.allowed_submission_mime)) then
      raise exception 'File type % is not permitted for submissions', v_mime
        using errcode = '23514';
    end if;
    if v_size is not null and v_size > s.max_submission_bytes then
      raise exception 'File exceeds the % byte limit for submissions', s.max_submission_bytes
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists validate_upload on storage.objects;
create trigger validate_upload
  before insert on storage.objects
  for each row execute function app.validate_resource_upload();

comment on function app.validate_resource_upload() is
  'Server-side MIME and size enforcement. Client-side validation is a convenience; this is the control.';
